Ft/unsubscribe from post
NSS-Day-Cohort-69/tabloid-hamburgers pull request #89
Opened 2024-05-31 19:03 UTC by rubygkendrick

User is able to unsubscribe from an author's posts

Files changed: PostDetails.jsx 
SubscriptionManager.js
SubscriptionController.cs

to test:
navigate to the post details view 
subscribe to a user, if you aren't already, and unsubscribe. 
go to PGAdmin and confirm that the unsubbed date was changed to now

closes #15

2024-05-31 20:36 UTC, LucasBress0n approved these changes
Tested and checked PgAdmin +10 Points to house Rubbindoor.

2024-05-31 20:45 UTC, Lincoln-WIlcox requested changes

2024-05-31 20:45 UTC, Lincoln-WIlcox commented on Controllers/SubscriptionController.cs
> +        Subscription subscriptionToCancel = _db.Subscriptions.SingleOrDefault(s => s.FollowerId == followerId && s.SubscriberId == subscriberId);
When unsubbing and resubbing, this will throw an error as there already exists a subscriber ('Sequence contains more than one element'). You'll need to make a check if the subscription has an unsub date to filter out inactive subscriptions

2024-05-31 20:45 UTC, Lincoln-WIlcox commented on client/src/components/PostDetails.jsx
> +        const subscriberId = post.author?.id
I'd remove the ? here. In the case that author is undefined, we want that to throw an error instead of setting `subscriberId` to undefined. This is because the case where you'd get an error for `author.id` not being defined would be easier to debug than the case of the fetch failing because undefined was passed. 

This is called the fail fast principle. If you're curious to learn more, [here's](https://medium.com/@christian.ppl/introduction-to-the-fail-fast-principle-in-software-development-865ccab28979) a great article about it.

2024-06-02 14:09 UTC, rubygkendrick commented on client/src/components/PostDetails.jsx
> +        const subscriberId = post.author?.id
changes implemented

2024-06-02 14:09 UTC, rubygkendrick commented on Controllers/SubscriptionController.cs
> +        Subscription subscriptionToCancel = _db.Subscriptions.SingleOrDefault(s => s.FollowerId == followerId && s.SubscriberId == subscriberId);
changes implemented

2024-06-03 14:19 UTC, Lincoln-WIlcox approved these changes

2024-06-03 14:42 UTC, merged