Current users post
NSS-Day-Cohort-69/tabloid-hamburgers pull request #96
Opened 2024-06-03 18:58 UTC by AngRod96

made endpoint to get users posts

2024-06-03 20:27 UTC, Lincoln-WIlcox requested changes

2024-06-03 20:27 UTC, Lincoln-WIlcox commented on Models/Post.cs
> -    [Required]
Why was this removed?

2024-06-03 20:27 UTC, Lincoln-WIlcox commented on Controllers/UsersPostsController.cs
> +    //[Authorize]
you probably meant to uncomment this

2024-06-04 14:44 UTC, Lincoln-WIlcox approved these changes

2024-06-05 16:54 UTC, rubygkendrick approved these changes

2024-06-06 20:34 UTC, merged