Added Tag Filter
NSS-Day-Cohort-69/tabloid-hamburgers pull request #98
Opened 2024-06-03 20:09 UTC by LucasBress0n

Purpose: Allows not only Categories but now tags to be filterable.

Files Changed:
Controllers/PostController.cs
Models/DTOs/GetPostsDTO.cs
Models/DTOs/GetPostsPostTagDTO.cs
Models/PostTag.cs
client/src/components/PostList.jsx

To test: 

At the Post View, Change tags Categories or both
C: #5

2024-06-03 20:18 UTC, rubygkendrick approved these changes
looks good to me

2024-06-04 15:02 UTC, LucasBress0n reviewed
Ty for teaching me parameters inside of a filter 😭

2024-06-04 15:13 UTC, Lincoln-WIlcox requested changes

2024-06-04 15:13 UTC, Lincoln-WIlcox commented on Controllers/PostController.cs
> +    // [Authorize]
this should be uncommented

2024-06-04 18:48 UTC, merged